include: package:flutter_lints/flutter.yaml

linter:
  rules:

bloc:
  rules:
    - prefer_bloc
    - avoid_flutter_imports

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
